### ISSUE TITLE
cannot build against zeek 3.1.1

### ISSUE THREAD

**Issue by m1357** [zeek/bro-netmap#6]
works with 2.6.1 source:
./configure --bro-dist=/root/bro-2.6.1/
Build Directory        : build
Bro Source Directory   : /root/bro-2.6.1
-- Bro executable      : /root/bro-2.6.1/build/src/bro
-- Bro source          : /root/bro-2.6.1
-- Bro build           : /root/bro-2.6.1/build
-- Bro install prefix  : /opt/app/bro
-- Bro plugin directory: /opt/app/bro/lib/bro/plugins
-- Bro debug mode      : false
-- Configuring done
-- Generating done
-- Build files have been written to: /root/bro-netmap/build

but if using 3.1.1 
 
./configure --bro-dist=/root/zeek-3.1.1
/root/zeek-3.1.1 does not appear to be a valid Bro source tree.

**Comment by m1357** [comment]
It also works in 3.0.3: 

./configure --bro-dist=/root/zeek-3.0.3
Build Directory        : build
Bro Source Directory   : /root/zeek-3.0.3
-- Zeek executable      : 
-- Zeek source          : /root/zeek-3.0.3
-- Zeek build           : /root/zeek-3.0.3/build
-- Zeek install prefix  : /usr/local/zeek
-- Zeek plugin directory: /usr/local/zeek/lib/zeek/plugins
-- Zeek debug mode      : false
-- Configuring done
-- Generating done
-- Build files have been written to: /root/bro-netmap/build

**Comment by m1357** [comment]
Looking at the configure script it is because bro-path-dev.in has been renamed to zeek-path-dev.in although install is still broken:

./configure --bro-dist=/root/zeek-3.1.1
Build Directory        : build
Bro Source Directory   : /root/zeek-3.1.1
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success
-- Zeek executable      : 
-- Zeek source          : /root/zeek-3.1.1
-- Zeek build           : /root/zeek-3.1.1/build
-- Zeek install prefix  : /opt/app/zeek
-- Zeek plugin directory: /opt/app/zeek/lib/zeek/plugins
-- Zeek debug mode      : false
-- Configuring done
-- Generating done
-- Build files have been written to: /root/bro-netmap/build
[root@itsec-prod-bro-4 ~/bro-netmap]# make                               
*** Error code 1 (ignored)
( cd build && make )
Scanning dependencies of target bro-plugin-Bro_Netmap
[ 20%] Creating __bro_plugin__ for Bro::Netmap
[ 20%] Built target bro-plugin-Bro_Netmap
Scanning dependencies of target copy-scripts-Bro_Netmap
[ 20%] Built target copy-scripts-Bro_Netmap
Scanning dependencies of target generate_outputs
[ 20%] Built target generate_outputs
Scanning dependencies of target Bro-Netmap.freebsd-amd64
[ 40%] Building CXX object CMakeFiles/Bro-Netmap.freebsd-amd64.dir/src/Plugin.cc.o
In file included from /root/bro-netmap/src/Plugin.cc:3:
/root/bro-netmap/src/Netmap.h:60:21: error: field has incomplete type 'struct pcap_pkthdr'
        struct pcap_pkthdr current_hdr;
                           ^
/root/zeek-3.1.1/src/iosource/PktSrc.h:12:8: note: forward declaration of 'pcap_pkthdr'
struct pcap_pkthdr;
       ^
In file included from /root/bro-netmap/src/Plugin.cc:3:
/root/bro-netmap/src/Netmap.h:61:21: error: field has incomplete type 'struct pcap_pkthdr'
        struct pcap_pkthdr last_hdr;
                           ^
/root/zeek-3.1.1/src/iosource/PktSrc.h:12:8: note: forward declaration of 'pcap_pkthdr'
struct pcap_pkthdr;
       ^
/root/bro-netmap/src/Plugin.cc:11:31: error: no type named 'PktSrcComponent' in namespace 'iosource'
        AddComponent(new ::iosource::PktSrcComponent("NetmapReader", "netmap", ::iosource::PktSrcComponent::LIVE, ::iosource::pktsrc::NetmapSource::InstantiateNetmap));
                         ~~~~~~~~~~~~^
/root/bro-netmap/src/Plugin.cc:12:31: error: no type named 'PktSrcComponent' in namespace 'iosource'
        AddComponent(new ::iosource::PktSrcComponent("NetmapReader", "vale", ::iosource::PktSrcComponent::LIVE, ::iosource::pktsrc::NetmapSource::InstantiateVale));
                         ~~~~~~~~~~~~^
4 errors generated.
*** Error code 1

Stop.
make[3]: stopped in /root/bro-netmap/build
*** Error code 1

Stop.
make[2]: stopped in /root/bro-netmap/build
*** Error code 1

Stop.
make[1]: stopped in /root/bro-netmap/build
*** Error code 1

Stop.
make: stopped in /root/bro-netmap

**Comment by sethhall** [comment]
This should be fixed now and working in the 2.0.0 release I just did.  At least it works with Zeek 4.0+ now.
